CREATE DATABASE IF NOT EXISTS xingqi_ai;
USE xingqi_ai;

CREATE TABLE orders(
id INT AUTO_INCREMENT PRIMARY KEY,
order_no VARCHAR(50),
email VARCHAR(100),
product VARCHAR(50),
amount INT,
status VARCHAR(30),
task_id VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
api_code VARCHAR(50),
price INT
);
